import 'react-quill/dist/quill.snow.css';
import {useState} from "react";
import {Navigate} from "react-router-dom";
import Editor from "../Editor";
// Open ai
const { Configuration, OpenAIApi } = require("openai");
const configuration = new Configuration({
  apiKey: process.env.REACT_APP_SECRET_KEY
});
const openai = new OpenAIApi(configuration);

export default function CreatePost() {
  const [title,setTitle] = useState('');
  const [summary,setSummary] = useState('');
  const [content,setContent] = useState('');
  const [files, setFiles] = useState('');
  const [redirect, setRedirect] = useState(false);

  // Open ai
  const [searchInput, setSearchInput] = useState('');
  const [output, setOutput] = useState('Output Generated by AI');

  async function searchAI(searchInput){
    const response = await openai.createCompletion({
      model: "text-davinci-003",
      prompt: searchInput,
      temperature: 1,
      max_tokens: 256,
      top_p: 1,
      frequency_penalty: 0,
      presence_penalty: 0,
    });
    const result = response.data.choices[0].text;
    setOutput(result);
  }
 
  
  async function createNewPost(ev) {
    const data = new FormData();
    data.set('title', title);
    data.set('summary', summary);
    data.set('content', content);
    data.set('file', files[0]);
    ev.preventDefault();
    const response = await fetch('http://localhost:4000/post', {
      method: 'POST',
      body: data,
      credentials: 'include',
    });
    if (response.ok) {
      setRedirect(true);
    }
  }

  if (redirect) {
    return <Navigate to={'/'} />
  }
  return (
    <>
      <h3>Ask AI Anything ?</h3>
      <input type="text" 
             placeholder="Eg : Give me heading on topic : dangers of AI"
             value={searchInput}
             onChange={ev => setSearchInput(ev.target.value)}
      />
      <button style={{backgroundColor:'rgb(64, 17, 64)', width:'6rem'}} onClick={()=>searchAI(searchInput)}>Search</button>
      <h3>Result : {output}</h3>

      <form onSubmit={createNewPost}>
      <input type="title"
             placeholder={'Title'}
             value={title}
             onChange={ev => setTitle(ev.target.value)} />
      <input type="summary"
             placeholder={'Summary'}
             value={summary}
             onChange={ev => setSummary(ev.target.value)} />
      <input type="file"
             onChange={ev => setFiles(ev.target.files)} />
      <Editor value={content} onChange={setContent} />
      <button style={{marginTop:'5px'}}>Create post</button>
    </form>

    
    </>
    
  );
}